version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/archiveOfLostTime
    restart: always

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=archiveOfLostTime
      - wiredTigerCacheSizeGB=0.5
    command: --wiredTigerCacheSizeGB 0.5
    mem_limit: 1g
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

volumes:
  mongo-data: 